<a href="https://colab.research.google.com/github/siwakornnn/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสร้างข้อมูล)
การเก็บข้อมูลหลายๆตัวอย่างเป็นระเบียบ

## `list()`
- เก็บอะไรก็ได้
- ลำดับในการเก็บมีความสำคัญ

In [ ]:
list_a = [1,2,3,4,5,6] #[ ] square brackets
list_a 

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b = ['ab' ,2,3.14,list_a]
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### indexing การชี้สมาชิกใน list ด้วย เลข]eดับของ list

In [ ]:
list_a[3]

4

In [ ]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b[3][3]

4

In [ ]:
list_a[-1] # index -1 คือ ตัวสุดท้ายของ list

In [ ]:
list_a[-4]

3

การสร้าง `list()`

In [ ]:
list_x1 = [] #แบบที่ 1
list_x2 = list() # แบบที่2

In [ ]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย `append()`

In [ ]:
list_x1.append(2)
list_x1

[2, 2]

In [ ]:
list_x1.append(5)
list_x1

[2, 2, 5]

In [ ]:
list_x1[0]

2

In [ ]:
list_x2

[]

In [ ]:
list_x2.append('ha')
list_x2

['ha']

### ลบสมาชิกจาก list

In [ ]:
list_x1.pop()

5

In [ ]:
list_x1.pop()

2

In [ ]:
list_x1.append('4')
list_x1

[2, '4', '4']

In [ ]:
list_x1.pop()

'4'

In [ ]:
list_x2.append('ha')
list_x2

['ha', 'ha']

`len()` ตรวจสอบจำนวนสมาชิกของ list

In [ ]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [ ]:
len(list_a)

6

### Sring is a list of characters

st_stat = 'Department of Statistics, Faculty of Science'

In [ ]:
st_stat[10]

' '

In [ ]:
len(st_stat)

44

### list Slicing `:`

`list[จุดเริ่มต้น(ทึบ):จุดสุดท้าย(โปร่ง)]`

`list[จุดเริ่มต้น(ทึบ):จุดสุดท้าย(โปร่ง):step]`

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_a[2]

3

#### colon

In [ ]:
list_a[-3:]   # : colon

[4, 5, 6]

In [ ]:
list_a[1:4]

[2, 3, 4]

In [ ]:
list_a[]

#### step

In [ ]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [ ]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

###`range()`

In [ ]:
range(21)

range(0, 21)

In [ ]:
a = list(range(21))

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย
(print ออกมาให้สวยงาม)
1. 12:3.:15
2. 13:41:07
3. 09:11:50
4. 21:30:15
5. 03:10:15

In [ ]:
#0.:00:00
a = 1*60*60
print(f'00:00:00 แปลงเป็นวินาทีได้ {a} วินาที')

00:00:00 แปลงเป็นวินาทีได้ 3600 วินาที


In [ ]:
# 1. 12:3.:15
Time = '12:30:15'
Time_1 = Time.split(':')
Time_1 = int(Time_1[0])*60*60 + int(Time_1[1])*60 + int(Time_1[2])
print(f'{Time} แปลงเป็นวินาที ได้ {Time_1} วินาที')

12:30:15 แปลงเป็นวินาที ได้ 45015 วินาที


In [ ]:
# 2. 09:11:50
Time = '09:11:50'
Time_1 = Time.split(':')
Time_1 = int(Time_1[0])*60*60 + int(Time_1[1])*60 + int(Time_1[2])
print(f'{Time} แปลงเป็นวินาที ได้ {Time_1} วินาที')

09:11:50 แปลงเป็นวินาที ได้ 33110 วินาที


In [ ]:
# 3. 13:41:07
Time = '13:41:07'
Time_1 = Time.split(':')
Time_1 = int(Time_1[0])*60*60 + int(Time_1[1])*60 + int(Time_1[2])
print(f'{Time} แปลงเป็นวินาที ได้ {Time_1} วินาที')

In [ ]:
# 4. 21:30:15
Time = '21:30:15'
Time_1 = Time.split(':')
Time_1 = int(Time_1[0])*60*60 + int(Time_1[1])*60 + int(Time_1[2])
print(f'{Time} แปลงเป็นวินาที ได้ {Time_1} วินาที')

21:30:15 แปลงเป็นวินาที ได้ 77415 วินาที


In [ ]:
# 5. 03:10:15
Time = '03:10:15'
Time_1 = Time.split(':')
Time_1 = int(Time_1[0])*60*60 + int(Time_1[1])*60 + int(Time_1[2])
print(f'{Time} แปลงเป็นวินาที ได้ {Time_1} วินาที')

03:10:15 แปลงเป็นวินาที ได้ 11415 วินาที


In [ ]:
# 1. 12:3.:15
Time = '12:30:15'
Time_1 = Time.split(':')
Time_1 = int(Time_1[0])*60*60 + int(Time_1[1])*60 + int(Time_1[2])
print(f'{Time} แปลงเป็นวินาที ได้ {Time_1} วินาที')

# Dictionary

- คล้าย list()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่มีความสำคัญ

### สร้าง Dictionary

In [1]:
dict_a = {1:'Happy','N':'New','2022':'Year'}   # { } curlybrackets

In [2]:
dict_a[1]

'Happy'

In [4]:
dict_a['N']

'New'

In [6]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [7]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

### การเพิ่มสมาชิกลงไปใน Dictionary

In [9]:
dict_a[7] = 3.14

In [10]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [12]:
dict_a['N'] = 'NNNNNEEEEWWWW'

In [13]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNNEEEEWWWW'}

## Numpy Array

- เก็บได้แค่ตัวเลข
- อ้างอิงโดยใช้ พิกัด (2มิติ มองเป็น Matrix)

In [14]:
import numpy

### 1D array

In [18]:
list_A = [1,2,3,4,5]

In [19]:
arr_a = numpy.array(list_A)

In [20]:
arr_a

array([1, 2, 3, 4, 5])

In [21]:
arr_a[0]

1

In [22]:
list_A[0]

1

In [23]:
5 * arr_a # Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [24]:
5*list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [25]:
arr_b = numpy.array([10,20,30,40,50])

In [30]:
arr_a.shape

(5,)

In [26]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

### 2D array

In [27]:
import numpy as np   # import มาใช้เป็นชื่อ np (ขี้เกียจพิมพ์ยาว)

In [28]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [29]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

### `np.zeros()`

In [33]:
arr2_3_5_0 = np.zeros((3,5))

In [34]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
arr2_3_5_0[1,2] = 9   # กำหนดค่า

In [36]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
arr2_3_5_0[1,2]    # ชี้

9.0

In [38]:
print(list_A)  # เปลี่ยนค่าใน list()
list_A[-1] = 'Christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Christmas']


### `np.ones()`

In [40]:
arr2_4_5_1 = np.ones((4,5))

In [41]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
arr2_4_5_200 = 200*np.ones((4,5))

In [43]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

## Matrix operations

#### การบวก ลบ matrix $M\pm N$ บวกลบตัวที่อยู่ตำแหน่งเดียวกัน

In [44]:
arr2_4_5_200 + arr2_4_5_0  # บวก ลบ matrix shape ต้องเท่ากัน

NameError: ignored

In [45]:
arr2_4_5_200 + arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

#### การคูณ matrix
- $aM$   คูณ matrix (scalar คูณกระจายเข้าไปทุกตัวของ matrix)
- $M\times N$  matrix คูณ matrix (แถวคูณหลัก)

$aM$ 

In [46]:
5 * arr_a # Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

$M\times N$ (dot product)
- (m,n) $\times$ (n,o) = (m,o) (Shape)

In [48]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [49]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

mat_b

In [52]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

In [53]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [54]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

In [55]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [56]:
np.dot(mat_c,mat_b)

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

In [57]:
mat_a * mat_b #คูณตำแหน่งเดียวกัน

array([[  2,   6,  25],
       [  8,  24, -49]])

In [59]:
mat_X = np.dot(mat_c,mat_b)
mat_X

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

### Matrix Slicing

In [60]:
mat_X[:2,:2]

array([[ 8, 16],
       [16, 32]])

1. 

HW3

1. สร้าง array ที่เป็นรูปต้น christmas
2. slice เลข 1 ออกมาจาก array HW3 ด้วยคำสั่ง slie แค่ครั้งเดียว

In [64]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [65]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Pandas Dataframe (แยกออกไปเป็น Notebook เฉพาะ)